#ifndef HGTXR_ZCU104_E2E_Q4W8A_DEFINES_H
#define HGTXR_ZCU104_E2E_Q4W8A_DEFINES_H

#ifndef HGTXR_TILING_FACTOR
#define HGTXR_TILING_FACTOR 1
#endif
#ifndef HGTXR_PARALLELISM_FACTOR
#define HGTXR_PARALLELISM_FACTOR 8
#endif
#ifndef HGTXR_BUS_WIDTH
#define HGTXR_BUS_WIDTH 256
#endif
#ifndef HGTXR_BIT_WIDTH
#define HGTXR_BIT_WIDTH 8
#endif
#ifndef HGTXR_WEIGHT_BIT_WIDTH
#define HGTXR_WEIGHT_BIT_WIDTH 4
#endif
#ifndef HGTXR_WEIGHT_INT_WIDTH
#define HGTXR_WEIGHT_INT_WIDTH 2
#endif
#ifndef HGTXR_BUFFER_SIZE
#define HGTXR_BUFFER_SIZE 256
#endif
#ifndef HGTXR_FIFO_DEPTH
#define HGTXR_FIFO_DEPTH 128
#endif
#ifndef HGTXR_ENABLE_CYCLIC_WEIGHT_PORTS
#define HGTXR_ENABLE_CYCLIC_WEIGHT_PORTS 1
#endif
#ifndef HGTXR_CYCLIC_MODEL_DIM
#define HGTXR_CYCLIC_MODEL_DIM 192
#endif
#ifndef HGTXR_CYCLIC_MLP_RATIO
#define HGTXR_CYCLIC_MLP_RATIO 4
#endif
#ifndef HGTXR_CYCLIC_WEIGHT_BLOCKS
#define HGTXR_CYCLIC_WEIGHT_BLOCKS 6
#endif
#ifndef HGTXR_E2E_BLOCKS
#define HGTXR_E2E_BLOCKS 6
#endif
#ifndef HGTXR_E2E_ATTN_UNITS
#define HGTXR_E2E_ATTN_UNITS 2
#endif
#ifndef HGTXR_E2E_MLP_UNITS
#define HGTXR_E2E_MLP_UNITS 2
#endif
#ifndef HGTXR_E2E_ATTN_PAR
#define HGTXR_E2E_ATTN_PAR 8
#endif
#ifndef HGTXR_E2E_WEIGHT_DEPTH
#define HGTXR_E2E_WEIGHT_DEPTH 381024
#endif
#ifndef HGTXR_E2E_ACTIVE_TOKENS
#define HGTXR_E2E_ACTIVE_TOKENS 196
#endif
#ifndef HGTXR_E2E_PATCH_GRID_H
#define HGTXR_E2E_PATCH_GRID_H 14
#endif
#ifndef HGTXR_E2E_PATCH_GRID_W
#define HGTXR_E2E_PATCH_GRID_W 14
#endif
#ifndef HGTXR_E2E_HEADS
#define HGTXR_E2E_HEADS 3
#endif
#ifndef HGTXR_E2E_HEAD_DIM
#define HGTXR_E2E_HEAD_DIM 64
#endif
#ifndef HGTXR_E2E_FF_DIM
#define HGTXR_E2E_FF_DIM 768
#endif
#ifndef HGTXR_E2E_DENSE_PAR
#define HGTXR_E2E_DENSE_PAR 8
#endif
#ifndef HGTXR_E2E_ACC_SCALE
#define HGTXR_E2E_ACC_SCALE 16
#endif
#ifndef HGTXR_USE_HGPIPE_LUT_MATH
#define HGTXR_USE_HGPIPE_LUT_MATH 1
#endif

#endif  // HGTXR_ZCU104_E2E_Q4W8A_DEFINES_H
