#ifndef HGTXR_ZCU104_CYCLIC_S0_DEFINES_H
#define HGTXR_ZCU104_CYCLIC_S0_DEFINES_H

#define HGTXR_TILING_FACTOR 1
#define HGTXR_PARALLELISM_FACTOR 1
#define HGTXR_BUS_WIDTH 128
#define HGTXR_BIT_WIDTH 16
#define HGTXR_BUFFER_SIZE 64
#define HGTXR_FIFO_DEPTH 16

#endif
