---
runtime:
  cudnn_enabled: true
  cudnn_benchmark: true
  cudnn_deterministic: false

dataloader:
  train:
    dataset:
      type: DavisWithMaskDataset
      root_path: /mnt/e/DATASET/eveye/DavisWithMaskDataset_labelled_subset
      split: train
      default_resolution: [256, 256]
      events_interpolation: causal_linear
      mode: rgb
    batch_size: 8
    shuffle: true
    drop_last: false
    num_workers: 4
    prefetch_factor: 2
    persistent_workers: true
    pin_memory: true

  val:
    dataset:
      type: DavisWithMaskDataset
      root_path: /mnt/e/DATASET/eveye/DavisWithMaskDataset_labelled_subset
      split: val
      default_resolution: [256, 256]
      events_interpolation: causal_linear
      mode: rgb
    batch_size: 8
    shuffle: false
    drop_last: false
    num_workers: 4
    prefetch_factor: 2
    persistent_workers: true
    pin_memory: true

model:
  type: UNet
  n_channels: 1
  n_classes: 2

train:
  max_epochs: 100
  check_val_every_n_epoch: 5
  optimizer:
    learning_rate: 1.0e-3
    weight_decay: 1.0e-5

val:
  ckpt_path:

trainer:
  accelerator: gpu
  devices: 1
  default_root_dir: /home/user/project/PRJXR-HBTXR/HBTXR/references/codebase/software/FACET/runs/unet_bs8_w4_cudnn_fp32_100e
  precision: 32-true

logger:
  type: tensorboard
  save_dir: /home/user/project/PRJXR-HBTXR/HBTXR/references/codebase/software/FACET/runs/logs
  name: RGBUNet_bs8_w4_cudnn_fp32_100e

callback:
  - type: ModelCheckpoint
    monitor: val_mean_distance
    auto_insert_metric_name: true
    save_top_k: 3
    mode: min
    every_n_epochs: 5
    save_last: true
    verbose: true
    filename: "{epoch:02d}-{val_mean_distance:.4f}"

  - type: TQDMProgressBar
    refresh_rate: 20

  - type: Timer

  - type: LearningRateMonitor
    logging_interval: epoch
