---
dataloader:
  train:
    dataset:
      type: DavisWithMaskDataset
      root_path: /home/kjm26/project/dataset/XR/EV_Eye/raw_data/DavisWithMaskDataset_labelled_subset
      split: train
      default_resolution: [256, 256]
      events_interpolation: causal_linear
      mode: rgb
    batch_size: 8
    shuffle: true
    drop_last: false
    num_workers: 0
    persistent_workers: false
    pin_memory: true

  val:
    dataset:
      type: DavisWithMaskDataset
      root_path: /home/kjm26/project/dataset/XR/EV_Eye/raw_data/DavisWithMaskDataset_labelled_subset
      split: val
      default_resolution: [256, 256]
      events_interpolation: causal_linear
      mode: rgb
    batch_size: 8
    shuffle: false
    drop_last: false
    num_workers: 0
    persistent_workers: false
    pin_memory: true

model:
  type: UNet
  n_channels: 1
  n_classes: 2

train:
  max_epochs: 70
  check_val_every_n_epoch: 1
  optimizer:
    learning_rate: 1.0e-3
    weight_decay: 1.0e-5

val:
  ckpt_path:

trainer:
  accelerator: auto
  devices: auto
  default_root_dir: /home/kjm26/project/PRJXR/HBTXR/references/codebase/software/FACET/runs/unet_subset

logger:
  type: tensorboard
  save_dir: /home/kjm26/project/PRJXR/HBTXR/references/codebase/software/FACET/runs/logs
  name: RGBUNet_local_subset

callback:
  - type: ModelCheckpoint
    monitor: val_mean_distance
    auto_insert_metric_name: true
    save_top_k: 3
    mode: min
    every_n_epochs: 1
    save_last: true
    verbose: true
    filename: "{epoch:02d}-{val_mean_distance:.4f}"

  - type: TQDMProgressBar
    refresh_rate: 1

  - type: Timer

  - type: LearningRateMonitor
    logging_interval: epoch
